version: "3.8"

volumes:
    redis:
        driver: ${VOLUMES_DRIVER}

networks:
    backend:
        driver: ${NETWORKS_DRIVER}

services:
################################################## Redis ##################################################
  redis:
    container_name: redis
    build: ./redis
    volumes:
        - ${DATA_PATH_HOST}/redsis:/data
    # command: --requirepass ${REDIS_PASSWORD}
    ports:
        - "${REDIS_PORT}:6379"
    networks:
        - backend